# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameTitle', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=2)),
                ('venueName', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
                ('visitorScore', models.IntegerField(default=0)),
                ('homeScore', models.IntegerField(default=0)),
                ('visitor1st', models.IntegerField(default=0)),
                ('visitor2nd', models.IntegerField(default=0)),
                ('visitor3rd', models.IntegerField(default=0)),
                ('visitor4th', models.IntegerField(default=0)),
                ('home1st', models.IntegerField(default=0)),
                ('home2nd', models.IntegerField(default=0)),
                ('home3rd', models.IntegerField(default=0)),
                ('home4th', models.IntegerField(default=0)),
                ('image1', models.ImageField(default='game_images/default_game_image.jpg', upload_to='game_images/')),
                ('image2', models.ImageField(blank=True, upload_to='game_images/')),
                ('image3', models.ImageField(blank=True, upload_to='game_images/')),
                ('image4', models.ImageField(blank=True, upload_to='game_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=25)),
                ('email', models.CharField(default='', max_length=40)),
                ('phone', models.CharField(default='', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=25)),
                ('jerseyNumber', models.IntegerField()),
                ('email', models.CharField(default='', max_length=40)),
                ('phone', models.CharField(default='', max_length=14)),
                ('image1', models.ImageField(default='player_images/default_player_image.jpg', upload_to='player_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(default='', max_length=45)),
                ('teamName', models.CharField(default='', max_length=45)),
                ('primaryColor', models.CharField(max_length=25)),
                ('secondaryColor', models.CharField(max_length=25)),
                ('year', models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2015)),
                ('image', models.ImageField(default='team_images/default_team_image.jpg', upload_to='team_images/')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='vaf_Api.Manager')),
                ('players', models.ManyToManyField(to='vaf_Api.Player')),
            ],
        ),
    ]
