# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image1',
            field=models.ImageField(default='game_images/default_game_image.jpg', upload_to='game_images/'),
        ),
        migrations.AddField(
            model_name='game',
            name='image2',
            field=models.ImageField(default='game_images/default_game_image.jpg', upload_to='game_images/'),
        ),
        migrations.AddField(
            model_name='game',
            name='image3',
            field=models.ImageField(default='game_images/default_game_image.jpg', upload_to='game_images/'),
        ),
        migrations.AddField(
            model_name='game',
            name='image4',
            field=models.ImageField(default='game_images/default_game_image.jpg', upload_to='game_images/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='jerseyNumber',
            field=models.IntegerField(),
        ),
    ]
