# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0003_auto_20160928_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image2',
            field=models.ImageField(blank=True, upload_to='player_images/'),
        ),
        migrations.AddField(
            model_name='player',
            name='image3',
            field=models.ImageField(blank=True, upload_to='player_images/'),
        ),
        migrations.AddField(
            model_name='player',
            name='image4',
            field=models.ImageField(blank=True, upload_to='player_images/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='image1',
            field=models.ImageField(default='player_images/default_player_image.jpg', upload_to='player_images/'),
        ),
    ]
