# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0003_remove_player_jerseynumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.CharField(default='', max_length=105),
        ),
    ]
