# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0004_auto_20160928_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='image4',
        ),
    ]
