# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0005_auto_20160929_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image2',
            field=models.ImageField(blank=True, upload_to='game_images/'),
        ),
        migrations.AddField(
            model_name='game',
            name='image3',
            field=models.ImageField(blank=True, upload_to='game_images/'),
        ),
        migrations.AddField(
            model_name='game',
            name='image4',
            field=models.ImageField(blank=True, upload_to='game_images/'),
        ),
    ]
