# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0005_remove_player_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ball',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='vaf_Api.Equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ballMfg',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ballType',
            field=models.CharField(default='', max_length=45),
        ),
    ]
