# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0006_auto_20160929_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.CharField(default='NA', max_length=40),
        ),
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.CharField(default='NA', max_length=14),
        ),
    ]
