# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0006_auto_20170118_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='awayTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awayTeam', to='vaf_Api.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='homeTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeTeam', to='vaf_Api.Team'),
        ),
    ]
