# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0007_auto_20161025_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='season',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.AddField(
            model_name='game',
            name='home1st',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='home2nd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='home3rd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='home4th',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='homeScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='visitor1st',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='visitor2nd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='visitor3rd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='visitor4th',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='visitorScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='team_images/default_team_image.jpg', upload_to='team_images/'),
        ),
        migrations.AddField(
            model_name='team',
            name='playerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='vaf_Api.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='year',
            field=models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2015),
        ),
    ]
