# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0008_auto_20161026_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
        migrations.RemoveField(
            model_name='team',
            name='playerId',
        ),
        migrations.RemoveField(
            model_name='team',
            name='year',
        ),
    ]
