# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0009_auto_20170118_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='location',
            name='venueName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
