# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0010_auto_20170118_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='location',
        ),
        migrations.AddField(
            model_name='game',
            name='venueName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='vaf_Api.Location'),
        ),
    ]
