# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0010_auto_20161026_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='new',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
