# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0011_auto_20170118_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='venueName',
            new_name='location',
        ),
    ]
