# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0012_remove_team_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(default='', max_length=14),
        ),
    ]
