# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0012_auto_20170118_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
