# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0013_auto_20161026_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cityName',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='team',
            name='teamName',
            field=models.CharField(default='', max_length=45),
        ),
    ]
