# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0014_auto_20161026_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='playerId',
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(to='vaf_Api.Player'),
        ),
    ]
