# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0014_auto_20170118_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.ManyToManyField(to='vaf_Api.Manager'),
        ),
    ]
