# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0016_auto_20170118_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
    ]
