# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0019_auto_20170118_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='managers',
            new_name='managerId',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='players',
            new_name='playerId',
        ),
    ]
