# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0021_remove_team_managerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='managerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='vaf_Api.Manager'),
        ),
    ]
