# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0023_auto_20170120_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='homeTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeTeamm', to='vaf_Api.Team'),
        ),
    ]
