# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0024_auto_20170120_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='homeTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeTeam', to='vaf_Api.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='managerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managerId', to='vaf_Api.Manager'),
        ),
    ]
