# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0025_auto_20170120_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='aboutOrgTeamParagraph',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='team',
            name='aboutOrgTeamParagraph2',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='team',
            name='imageInfo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='vafEstablished',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
