# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0028_auto_20170123_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vafEstablished', models.DateField()),
                ('aboutOrgTeamParagraph', models.TextField(default='', max_length=400)),
                ('aboutOrgTeamParagraph2', models.TextField(default='', max_length=400)),
            ],
        ),
    ]
