# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0031_auto_20170123_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='imageInfo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='playerInfo',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='team',
            name='imageInfo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
