# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0032_auto_20170123_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameSummary',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='game',
            name='gameSummary2',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='game',
            name='image1Info',
            field=models.CharField(default='', max_length=100),
        ),
    ]
