# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0034_remove_team_playerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='playerId',
            field=models.ManyToManyField(to='vaf_Api.Player'),
        ),
    ]
