# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0035_team_playerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='imageInfo',
            new_name='image1Info',
        ),
    ]
