# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0036_auto_20170124_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='franchise',
            old_name='aboutOrgTeamParagraph',
            new_name='aboutOrgTeam1',
        ),
        migrations.RenameField(
            model_name='franchise',
            old_name='aboutOrgTeamParagraph2',
            new_name='aboutOrgTeam2',
        ),
        migrations.AddField(
            model_name='franchise',
            name='aboutVafTeam1',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='franchise',
            name='franchiseLogo',
            field=models.ImageField(default='franchise_images/default_franchise_image.jpg', upload_to='franchise_images/'),
        ),
    ]
