# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0037_auto_20170127_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='franchiseId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='franchiseId', to='vaf_Api.Franchise'),
        ),
    ]
