# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0039_franchise_aboutvafteam2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='ball',
            new_name='equipmentId',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='location',
            new_name='locationId',
        ),
    ]
