# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaf_Api', '0041_auto_20170128_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='cityName',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='franchise',
            name='teamName',
            field=models.CharField(default='', max_length=45),
        ),
    ]
